### ISSUE TITLE
Fitting results

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpofit#64]
At the moment, fitting results work but are not very highly refined. I think we need to nail down a few things:

  1. The concept of a base result that is literally just ground truth and final shape. This will become the equivalent of the ``SerializableResult``. 
    - How do we attach these results back to images, yet keep the file size down? Just attach the image? No image? Path? Some sort of ID?
  2. Check the current hierarchy makes sense - do all the fitting results such as the AAM results have all the information we want like appearance parameters etc? Are they all available under sensible names?
  3. Visualization - Can we do more advanced visualization for things like AAM results? Can the widgets just handle this on the fly or do we need multiple visualization methods?

This is also likely important for making MenpoBench nice and consistent with MenpoFit.

**Comment by patricksnape** [comment]
This should be sorted by #9

**Comment by nontas** [comment]
1 and 2 are handled by https://github.com/menpo/menpofit/pull/83 and https://github.com/menpo/menpowidgets/pull/9. 

3 is a good point that is not supported yet. Specifically, to have AAM widgets that also support the visualization of warped images and reconstructions. However, since https://github.com/menpo/menpofit/pull/83, the ``AAMResult`` no longer holds the actual model and fitter objects. ``warped_images()`` and ``appearance_reconstructions()`` are actually methods of an ``AAMFitter`` subclass. Thus, it may be a bit tricky to have such a widget...

**Comment by patricksnape** [comment]
No its all good -  we will just have a separate widget I think - later down the line. It makes more sense for that to be part of the Model vis rather than the AAM vis.

**Comment by patricksnape** [comment]
Closing in favour of just waiting for a request for that widget.
